//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zeje.Staticize_.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlogPost
    {
        public int id { get; set; }
        public Nullable<int> categoryId { get; set; }
        public string title { get; set; }
        public string content { get; set; }
        public int postType { get; set; }
        public string summary { get; set; }
        public string tagName { get; set; }
        public int commentCount { get; set; }
        public Nullable<int> viewCount { get; set; }
        public Nullable<int> rssCount { get; set; }
        public Nullable<bool> isAllowComment { get; set; }
        public bool isForbidAnonymousComment { get; set; }
        public bool isVisible { get; set; }
        public Nullable<bool> onlyRegister { get; set; }
        public int state { get; set; }
        public string addPerson { get; set; }
        public System.DateTime addTime { get; set; }
        public string updatePerson { get; set; }
        public System.DateTime updateTime { get; set; }
        public string deletePerson { get; set; }
        public Nullable<System.DateTime> deleteTime { get; set; }
    }
}
