//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zeje.Staticize_.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlogCategory
    {
        public int id { get; set; }
        public string name { get; set; }
        public string slug { get; set; }
        public string type { get; set; }
        public Nullable<int> parentId { get; set; }
        public Nullable<int> countChildNumber { get; set; }
        public int countParentNumber { get; set; }
        public int state { get; set; }
        public Nullable<System.DateTime> publishTime { get; set; }
        public Nullable<int> orderId { get; set; }
        public string addPerson { get; set; }
        public System.DateTime addTime { get; set; }
        public string updatePerson { get; set; }
        public System.DateTime updateTime { get; set; }
        public string deletePerson { get; set; }
        public Nullable<System.DateTime> deleteTime { get; set; }
    }
}
